import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/shared/header";
import Footer from "@/components/shared/footer";
import GlobalNotifier from "@/components/shared/Notifier";
import { AuthProvider } from "@/context/AuthContext";
import ErrorBoundary from "@/components/shared/ErrorBoundary";
import { UserProfileProvider } from "@/context/UserProfileContext";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Muawza",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ErrorBoundary>

        
         <AuthProvider>
            <UserProfileProvider>

            

        
              <Header />
        
        {children}
        </UserProfileProvider>
           <Footer />
            <GlobalNotifier />
             </AuthProvider>
             </ErrorBoundary>
      </body>
    </html>
  );
}
